[package]
name = "dice-mfg-msgs"
version = "0.2.1"
edition = "2021"

[dependencies]
corncobs.workspace = true
hubpack.workspace = true
serde = { workspace = true, features = ["derive"] }
serde-big-array.workspace = true
thiserror = { workspace = true, optional = true }
zerocopy.workspace = true

[features]
std = ["thiserror"]
