[package]
name = "attest-data"
version = "0.1.0"
edition = "2021"

[dependencies]
hubpack.workspace = true
thiserror = { workspace = true, optional = true }
salty.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_with = { workspace = true, features = ["macros"] }
sha3.workspace = true

[features]
std = ["thiserror"]
