[package]
name = "dice-cert-tmpl"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[dependencies]
clap = { version = "4", features = ["derive"] }
dice-mfg-msgs = { path = "../dice-mfg-msgs" }
pem = "1"
salty = "0.2"
tempfile = "3"
