[package]
name = "dice-cert-tmpl"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[dependencies]
clap = { workspace = true, features = ["derive"] }
dice-mfg-msgs = { path = "../dice-mfg-msgs" }
pem.workspace = true
salty.workspace = true
tempfile.workspace = true
