name: license-check
on: pull_request
permissions:
  contents: read

jobs:
  license:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Check License Header
      uses: apache/skywalking-eyes/header@21648e752a1dad42cb46b50b38e77f0a8f15219c
